gantt
title Planificación Proyecto Seminario 2
dateFormat  DD-MM-YYYY
section Introducción
Resumen             :a1, after a9, 04-12-2020
Motivación          :a2, 24-08-2020, 2w
Hipótesis           :a3, after a2, 2w
Objetivos           :a4, after a3, 2w
section Metodología
Primera versión revisión literatura          :a5, 24-08-2020  , 8w
Segunda versión revisión literatura          :a6, after a5  , 6w
Descripción Metodología      :a7, after a2  , 04-12-2020
Bibliografía                 :a8, 30-11-2020  , 04-12-2020
section Gestión
Plan de trabajo              :a9, after a4  , 2w
Recursos requeridos          :a10, after a9  , 2w
