gantt
title Planificación Proyecto Seminario 2
dateFormat  DD-MM-YYYY
section Introducción
Resumen             :a10, after a10, 27-11-2020
Motivación          :a2, 24-08-2020, 11-09-2020
Hipótesis           :a3, after a2, 2w
Objetivos           :a4, after a3, 2w
section Metodología
Primera versión literatura          :a5, 24-08-2020  , 8w
Segunda versión literatura          :a6, after a5  , 6w
Primera versión Metodología      :a7, after a2  , 6w
Segunda versión Metodología          :a11, after a5  , 6w
Bibliografía                 :a8, 30-11-2020  , 04-12-2020
section Gestión
Plan de trabajo              :a9, after a5  , 2w
Recursos requeridos          :a10, after a9  , 2w
